
#This config houses all the extra spell and spell mechanics
#If you're looking to change the spell stats instead or disable/enable spells... Go to iron's spellbooks server config file
[spells]

	[spells.annihilation]
		#If Annihilation spell can cause blocks to break/create explosion || Default: true
		cause_explosion = true
		#If Annihilation spell can cause fire || Automatically disabled if cause_explosion is disabled || Default: true
		cause_fire = true

	[spells.aerial_collapse]
		#Should bosses take less percent-based damage from Aerial Collapse? || less than 1.0 will make them take less damage || Default 1.0
		#Range: 0.1 ~ 1.0
		bosses_take_less_damage = 1.0

	[spells.summon]
		#Limit the number of active 'Group' summon spells to one at a time || Default: true
		limit_group_summon = true
		#Limit the number of active 'Kaiju' summon spells to one at a time || Default: true
		limit_kaiju_summon = true
		#Limit the number of active 'Miniboss' summon spells to one at a time || Default: true
		limit_miniboss_summon = true

	[spells.death_laser]
		#Should DeathLaser break blocks || Default: true
		should_break_blocks = true
		#Should DeathLaser spell deal magic damage (default boss behavior/Ignore armor/less integration with spell power & resist attributes) || Default: false
		should_deal_magic_damage = false

	[spells.abyssal_blast]
		#Should Abyssal Blast break blocks || Default: true
		should_break_blocks = true
		#Should Abyssal Blast spell deal magic damage (default boss behavior/Ignore armor/less integration with spell power & resist attributes) || Default: false
		should_deal_magic_damage = false

#Staff, Spellbooks and other this kind of thing
[staff_spellbooks]

	[staff_spellbooks.titanlord_scepter]
		#If Titanlord Scepter should grant a recast to Annihilation spell || Default: true
		grant_annihilation_recast = true
		#Damage Multiplier || Default 1.0
		#Range: 0.0 ~ 10.0
		damage_multiplier = 1.0
		#Attack Speed Multiplier || Default 1.0
		#Range: 0.0 ~ 10.0
		attack_speed_multiplier = 1.0
		#Variant Spell Power Multiplier || MULTIPLY_BASE || Default 1.0
		#Range: 0.0 ~ 10.0
		variant_spell_power_multiplier = 1.0
		#Cooldown Reduction Multiplier || MULTIPLY_BASE || Default 1.0
		#Range: 0.0 ~ 10.0
		cooldown_reduction_multiplier = 1.0
		#Mana Regen Multiplier || MULTIPLY_BASE || Default 1.0
		#Range: 0.0 ~ 10.0
		mana_regen_multiplier = 1.0

	[staff_spellbooks.archive_of_abyssal_secrets]
		#Max Mana Multiplier || ADDITION || Default 1.0
		#Range: 0.0 ~ 10.0
		max_mana_multiplier = 1.0
		#Ender Spell Power Multiplier || MULTIPLY_BASE || Default 1.0
		#Range: 0.0 ~ 10.0
		ender_spell_power_multiplier = 1.0
		#Eldritch Spell Power Multiplier || MULTIPLY_BASE || Default 1.0
		#Range: 0.0 ~ 10.0
		eldritch_spell_power_multiplier = 1.0

	[staff_spellbooks.chronicles_of_the_firelord]
		#Max Mana Multiplier || ADDITION || Default 1.0
		#Range: 0.0 ~ 10.0
		max_mana_multiplier = 1.0
		#Fire Spell Power Multiplier || MULTIPLY_BASE || Default 1.0
		#Range: 0.0 ~ 10.0
		fire_spell_power_multiplier = 1.0
		#Cooldown Reduction Multiplier || MULTIPLY_BASE || Default 1.0
		#Range: 0.0 ~ 10.0
		cooldown_reduction_multiplier = 1.0

	[staff_spellbooks.shellbound]
		#Max Mana Multiplier || ADDITION || Default 1.0
		#Range: 0.0 ~ 10.0
		max_mana_multiplier = 1.0
		#Cooldown Reduction Multiplier || MULTIPLY_BASE || Default 1.0
		#Range: 0.0 ~ 10.0
		cooldown_reduction_multiplier = 1.0
		#Nature Spell Power Multiplier || MULTIPLY_BASE || Default 1.0
		#Range: 0.0 ~ 10.0
		nature_spell_power_multiplier = 1.0

	[staff_spellbooks.the_accused_codex]
		#Max Mana Multiplier || ADDITION || Default 1.0
		#Range: 0.0 ~ 10.0
		max_mana_multiplier = 1.0
		#Cooldown Reduction Multiplier || MULTIPLY_BASE || Default 1.0
		#Range: 0.0 ~ 10.0
		cooldown_reduction_multiplier = 1.0
		#Ice Spell Power Multiplier || MULTIPLY_BASE || Default 1.0
		#Range: 0.0 ~ 10.0
		ice_spell_power_multiplier = 1.0

	[staff_spellbooks.codec_of_crushing_depths]
		#Max Mana Multiplier || ADDITION || Default 1.0
		#Range: 0.0 ~ 10.0
		max_mana_multiplier = 1.0
		#Cooldown Reduction Multiplier || MULTIPLY_BASE || Default 1.0
		#Range: 0.0 ~ 10.0
		cooldown_reduction_multiplier = 1.0
		#Aqua Spell Power Multiplier || MULTIPLY_BASE || Default 1.0
		#Range: 0.0 ~ 10.0
		aqua_spell_power_multiplier = 1.0

	[staff_spellbooks.guide_to_watery_whispers]
		#Max Mana Multiplier || ADDITION || Default 1.0
		#Range: 0.0 ~ 10.0
		max_mana_multiplier = 1.0
		#Mana Regen Multiplier || MULTIPLY_BASE || Default 1.0
		#Range: 0.0 ~ 10.0
		mana_regen_multiplier = 1.0
		#Aqua Spell Power Multiplier || MULTIPLY_BASE || Default 1.0
		#Range: 0.0 ~ 10.0
		aqua_spell_power_multiplier = 1.0

	[staff_spellbooks.wand_of_final_light]
		#Damage Multiplier || Default 1.0
		#Range: 0.0 ~ 10.0
		damage_multiplier = 1.0
		#Attack Speed Multiplier || Default 1.0
		#Range: 0.0 ~ 10.0
		attack_speed_multiplier = 1.0
		#Ender Spell Power Multiplier || MULTIPLY_BASE || Default 1.0
		#Range: 0.0 ~ 10.0
		ender_spell_power_multiplier = 1.0
		#Cooldown Reduction Multiplier || MULTIPLY_BASE || Default 1.0
		#Range: 0.0 ~ 10.0
		cooldown_reduction_multiplier = 1.0
		#Cast Time Reduction Multiplier || MULTIPLY_BASE || Default 1.0
		#Range: 0.0 ~ 10.0
		cast_time_reduction_multiplier = 1.0

	[staff_spellbooks.diamanticArchive]
		#Max Mana Multiplier || ADDITION || Default 1.0
		#Range: 0.0 ~ 10.0
		max_mana_multiplier = 1.0
		#Lightning Spell Power Multiplier || MULTIPLY_BASE || Default 1.0
		#Range: 0.0 ~ 10.0
		lightning_spell_power_multiplier = 1.0

	[staff_spellbooks.stormEmpressStaff]
		#Damage Multiplier || Default 1.0
		#Range: 0.0 ~ 10.0
		damage_multiplier = 1.0
		#Attack Speed Multiplier || Default 1.0
		#Range: 0.0 ~ 10.0
		attack_speed_multiplier = 1.0
		#Aqua Spell Power Multiplier || MULTIPLY_BASE || Default 1.0
		#Range: 0.0 ~ 10.0
		aqua_spell_power_multiplier = 1.0
		#Lightning Spell Power Multiplier || MULTIPLY_BASE || Default 1.0
		#Range: 0.0 ~ 10.0
		lightning_spell_power_multiplier = 1.0
		#Mana Regen Multiplier || MULTIPLY_BASE || Default 1.0
		#Range: 0.0 ~ 10.0
		mana_regen_multiplier = 1.0

