
#Avaritia Expand Common Config
[block]
	#The explosion radius of InfinityTNT
	#Range: 0 ~ 1000
	"InfinityTNT Radius" = 100
	#The explosion length of InfinityTNT
	#Range: -500 ~ 0
	"InfinityTNT Length" = -40
	#Can InfinityTNT break bedrock?
	"InfinityTNT Break BedRock" = true
	#Can InfinityTNT break obsidian?
	"InfinityTNT Break Obsidian" = true

