
#Avaritia Common Config
[tools]

	[tools.config]

		[tools.config.avaritia]
			#config.avaritia.is_merge_matter_cluster.tooltip
			is_merge_matter_cluster = true
			#config.avaritia.sword_range_damage.tooltip
			#Range: 100 ~ 100000
			sword_range_damage = 10000
			#config.avaritia.sword_attack_range.tooltip
			#Range: 8 ~ 64
			sword_attack_range = 32
			#config.avaritia.is_sword_attack_item_entity.tooltip
			is_sword_attack_item_entity = false
			#config.avaritia.is_sword_attack_lightning.tooltip
			is_sword_attack_lightning = false
			#config.avaritia.is_sword_attack_endless.tooltip
			is_sword_attack_endless = true
			#config.avaritia.sub_arrow_damage.tooltip
			#Range: 100 ~ 100000
			sub_arrow_damage = 10000
			#config.avaritia.pickaxe_break_range.tooltip
			#Range: 2 ~ 32
			pickaxe_break_range = 8
			#config.avaritia.shovel_break_range.tooltip
			#Range: 2 ~ 32
			shovel_break_range = 8
			#config.avaritia.singularity_time_required.tooltip
			#Range: > 0
			singularity_time_required = 240
			#config.avaritia.growth_soul_farmland.tooltip
			#Range: 0.0 ~ 1.0
			growth_soul_farmland = 0.8
			#config.avaritia.blade_slash_damage.tooltip
			#Range: > 0
			blade_slash_damage = 200
			#config.avaritia.blade_slash_radius.tooltip
			#Range: 5 ~ 100
			blade_slash_radius = 10
			#config.avaritia.is_sword_attack_projectile.tooltip
			is_sword_attack_projectile = false

[emc]

	[emc.config]

		[emc.config.avaritia]
			#config.avaritia.neutron_pile_emc.tooltip
			#Range: > 0
			neutron_pile_emc = 100
			#config.avaritia.vanilla_totem_emc.tooltip
			#Range: > 0
			vanilla_totem_emc = 1000
			#config.avaritia.blaze_cube_emc.tooltip
			#Range: > 0
			blaze_cube_emc = 30568
			#config.avaritia.bedrock_emc.tooltip
			#Range: > 0
			bedrock_emc = 10

[channel]

	[channel.config]

		[channel.config.avaritia]
			#config.avaritia.max_channels_pre_player.tooltip
			#Range: 4 ~ 64
			max_channels_pre_player = 16
			#config.avaritia.max_public_channels.tooltip
			#Range: 32 ~ 1024
			max_public_channels = 128
			#config.avaritia.channel_fast_update_rate.tooltip
			#Range: 1 ~ 40
			channel_fast_update_rate = 1
			#config.avaritia.channel_full_update_rate.tooltip
			#Range: 20 ~ 1200
			channel_full_update_rate = 40

[misc]

	[misc."immortal item entity"]

		[misc."immortal item entity".config]

			[misc."immortal item entity".config.avaritia]
				#config.avaritia.endless_item_entity_speed.tooltip
				#Range: 1.0 ~ 50.0
				endless_item_entity_speed = 3.0
				#config.avaritia.endless_item_entity_range.tooltip
				#Range: 1.0 ~ 10000.0
				endless_item_entity_range = 1000.0

	[misc.config]

		[misc.config.avaritia]
			#config.avaritia.use_advance_tooltips.tooltip
			use_advance_tooltips = false
			#config.avaritia.infinity_elytra_flying_speed.tooltip
			#Range: 1.0 ~ 10.0
			infinity_elytra_flying_speed = 1.5
			#config.avaritia.boot_speed_base.tooltip
			#Range: 0.01 ~ 1.0
			boot_speed_base = 0.1
			#config.avaritia.boot_speed_flying_multiplier.tooltip
			#Range: 0.1 ~ 5.0
			boot_speed_flying_multiplier = 1.1
			#config.avaritia.boot_speed_swimming_multiplier.tooltip
			#Range: 0.1 ~ 5.0
			boot_speed_swimming_multiplier = 1.2
			#config.avaritia.boot_speed_sneaking_multiplier
			#Range: 0.01 ~ 1.0
			boot_speed_sneaking_multiplier = 0.1
			#config.avaritia.boot_speed_backward_multiplier.tooltip
			#Range: 0.01 ~ 1.0
			boot_speed_backward_multiplier = 0.25
			#config.avaritia.boot_speed_strafing_multiplier
			#Range: 0.01 ~ 1.0
			boot_speed_strafing_multiplier = 0.45
			#config.avaritia.boot_speed_sprinting_multiplier
			#Range: 0.01 ~ 1.0
			boot_speed_sprinting_multiplier = 0.2

