#存储UI搜索按钮值 (除非你知道你在做什么，否则不要手动修改)
#Allowed Values: ENABLED, DISABLED, SORT_DEFAULT, SORT_QUANTITY, SORT_NAME, SORT_MODID
ui_sort_button = "SORT_DEFAULT"
#存储UI倒序按钮值 (除非你知道你在做什么，否则不要手动修改)
#Allowed Values: ENABLED, DISABLED, SORT_DEFAULT, SORT_QUANTITY, SORT_NAME, SORT_MODID
ui_reverse_button = "DISABLED"
#存储UI搜索按钮值 (除非你知道你在做什么，否则不要手动修改)
#Allowed Values: ENABLED, DISABLED, SORT_DEFAULT, SORT_QUANTITY, SORT_NAME, SORT_MODID
ui_search_button = "DISABLED"
#决定打开菜单时是否显示合成槽
#Allowed Values: ENABLED, DISABLED, SORT_DEFAULT, SORT_QUANTITY, SORT_NAME, SORT_MODID
ui_craft_button = "DISABLED"
#存储UI当前显示的总页数 (除非你知道你在做什么，否则不要手动修改)
#Range: 2 ~ 99
ui_page_num = 5
#存储UI搜索框内容 (除非你知道你在做什么，否则不要手动修改)
ui_search = ""
#决定工艺菜单关闭时，物品优先转移的方向；启用则优先向存储，关闭则优先向背包
#Allowed Values: ENABLED, DISABLED, SORT_DEFAULT, SORT_QUANTITY, SORT_NAME, SORT_MODID
ui_craft_return_button = "DISABLED"
#是否允许网络接口将资源送入网络
interface_can_receive_resource = true
#是否允许网络接口从网络提取标记的资源
interface_can_output_resource = true
#是否允许网络接口将内容物弹出到附近容器
interface_can_pop_resource = true
#网络接口有多少个槽位实际可用？
#注意：仅在确定需要时使用，后续版本更新会将其移除并添加其他替代方案，会保证存档兼容。
#Range: 1 ~ 27
interface_usable_capacity = 27
#是否与JEI或EMI同步搜索
search_text_with_jei_emi = true

