
["Animal Settings"]

	["Animal Settings"."Pig:"]
		#If true, Pigs can be tempted and bred using Fungi Delight mushrooms.
		enablePigFoods = true
		#If true, Pigs can randomly dig up items from tagged blocks (Podzol, Rooted dirt etc...)
		enablePigDigging = true
		#If true, breeding pigs with Truffles gives a chance for twins/triplets.
		enablePigExtraBaby = true
		#The probability per tick that a pig will attempt to dig a podzol block
		#Formula: 1 / value = Average Ticks.
		#Default: 0.00025 (Approx. 1 attempt every 3 min 20 sec).
		#Range: 0.0 (Disabled) to 1.0 (Every tick).
		#Range: 0.0 ~ 1.0
		chancePigDigging = 2.5E-4

	["Animal Settings"."Sniffer:"]
		#If true, Sniffers have a chance to drop Truffles when digging.
		enableSnifferTruffle = true

	["Animal Settings"."Wolf:"]
		#If true, Tamed Wolves can be used to sniff and locate Truffle Dirt blocks
		enableWolfHuntTruffle = true

["Effect Settings"]
	#If true, the Burrowing effect is enabled and craftable.
	enableBurrowingEffect = true
	#If true, the Weak Stomach effect is enabled.
	enableWeakStomachEffect = true
	#List of Item IDs that trigger the Weak Stomach effect (e.g. 'minecraft:milk_bucket', 'some_mod:skibidi_soup').
	"Trigger Items" = []

["Trade Settings"]
	#If true, adds Fungi Delight trades to Farmers and Wandering Traders.
	enableVillagerTrades = true
	#If true, the Wandering Trader can sell Fungi Delight items.
	enableWanderingTraderTrades = true

#Generation settings. Lower values = More Frequent generation.
#Set value to 0 to disable the feature entirely.
["World-gen Settings"]

	["World-gen Settings"."Huge Mushroom Generation"]
		#Average number of chunks between attempts to generate Huge Inky Caps.
		#Default: 3
		#Range: > 0
		hugeInkyCapRarity = 3
		#Average number of chunks between attempts to generate Huge Morels.
		#Default: 4
		#Range: > 0
		hugeMorelRarity = 4

	["World-gen Settings"."Mushroom Colony Patches"]
		#Average number of chunks between attempts to generate Inky Cap Colonies.
		#Default: 15
		#Range: > 0
		inkyCapColonyRarity = 15
		#Average number of chunks between attempts to generate Morel Colonies.
		#Default: 15
		#Range: > 0
		morelColonyRarity = 15

	["World-gen Settings"."Mushroom Patches Generation"]
		#Rarity of Inky Caps in standard Overworld biomes.
		#Default: 768
		#Range: > 0
		inkyCapStandardRarity = 768
		#Rarity of Morels in standard Overworld biomes.
		#Default: 384
		#Range: > 0
		morelStandardRarity = 384
		#Rarity of Inky Caps in Mushroom Fields.
		#Default: 16
		#Range: > 0
		inkyCapMushroomFieldRarity = 16
		#Rarity of Morels in Mushroom Fields.
		#Default: 12
		#Range: > 0
		morelMushroomFieldRarity = 12
		#Rarity of Inky Caps in Tagged biomes.
		#Default: 64
		#Range: > 0
		inkyCapTaggedRarity = 64
		#Rarity of Morels in Tagged biomes.
		#Default: 32
		#Range: > 0
		morelTaggedRarity = 32

	["World-gen Settings"."Truffle Ore Generation"]
		#Average number of chunks between Rooted Dirt blobs.
		#Default: 3
		#Range: > 0
		rootedDirtBlobRarity = 3
		#Average number of chunks between Truffle Dirt Ores.
		#Note: This replaces Rooted Dirt generated by the config above.
		#Default: 1
		#Range: > 0
		truffleDirtOreRarity = 1

