
[cookery]
	#Whether the Satiated Shield effect should absorb excess damage beyond its capacity.
	SatiatedShieldAbsorbExcessDamage = true
	#Whether enabling the Satiated Shield effect.
	SatiatedShieldAbsorbEnabled = true

