
[functions]
	logging = true
	revive = true
	locate = true

[revive]
	aggro = false
	totem = true

[vehicle_control]
	full = true
	rotate = true

[logging]
	disable_blockup = false

[misc]
	self_rescue = true

