
[base]
	#烈焰加农魂石魔符伤害
	#Range: 0.0 ~ 2.147483647E9
	firenando_soul_stone_damage = 1.0
	#烈焰加农魂石减免
	#Range: 0.0 ~ 2.147483647E9
	firenando_soul_stone_cast = 10.0
	#塞壬魂石
	#Range: 0.0 ~ 2.147483647E9
	siren_soul_stone = 1.0
	#荒野魂石伤害
	#Range: 0.0 ~ 2.147483647E9
	wilden_soul_stone_damage = 2.0
	#荒野魂石最大魔源
	#Range: 0.0 ~ 2.147483647E9
	wilden_soul_stone_mana = 0.2
	#荒野魂石再生
	#Range: 0.0 ~ 2.147483647E9
	wilden_soul_stone_re = 0.1
	#至高木魂石爆炸等级
	#Range: 0.0 ~ 2.147483647E9
	archwood_soul_stone_red = 1.0
	#至高木魂石冻结等级
	#Range: 0.0 ~ 2.147483647E9
	archwood_soul_stone_blue = 1.0
	#至高木魂石debuff时长
	#Range: 0.0 ~ 2.147483647E9
	archwood_soul_stone_time = 5.0
	#至高木魂石Debuff概率
	#Range: 0.0 ~ 2.147483647E9
	archwood_soul_stone_chance = 0.1
	#至高木魂石康复等级
	#Range: 0.0 ~ 2.147483647E9
	archwood_soul_stone_green = 1.0
	#至高木魂石护盾等级
	#Range: 0.0 ~ 2.147483647E9
	archwood_soul_stone_purple = 1.0
	#紫水晶傀儡魂石状态等级
	#Range: 0.0 ~ 2.147483647E9
	amethyst_golem_soul_stone_level = 1.0
	#紫水晶傀儡魂石击退抗性
	#Range: 0.0 ~ 2.147483647E9
	amethyst_golem_soul_stone = 0.3
	#薇克精魂石负面状态时长降低
	#Range: 0.0 ~ 2.147483647E9
	wixie_soul_stone_down = 0.3
	#薇克精魂石正面状态时长提升
	#Range: 0.0 ~ 2.147483647E9
	wixie_soul_stone_up = 0.2
	#书龙魂石魔符伤害
	#Range: 0.0 ~ 2.147483647E9
	bookwyrm_soul_stone_damage = 2.0
	#书龙魂石减免
	#Range: 0.0 ~ 2.147483647E9
	bookwyrm_soul_stone_cast = 20.0
	#星宝石兽魂石移速
	#Range: 0.0 ~ 2.147483647E9
	starbuncle_soul_stone = 0.4
	#风转草魂石消耗减免
	#Range: 0.0 ~ 2.147483647E9
	whirlisprig_soul_stone_cast = 10.0
	#风转草魂石额外回复饱食度
	#Range: 0.0 ~ 2.147483647E9
	whirlisprig_soul_stone_food = 0.5
	#德格米魂石额外掉落物
	#Range: 0.0 ~ 2.147483647E9
	drygmy_soul_stone_drop = 1.0
	#德格米魂石魔艺伤害
	#Range: 0.0 ~ 2.147483647E9
	drygmy_soul_stone_damage = 1.0
	#魔源魂石魔源伤害
	#Range: 0.0 ~ 2.147483647E9
	ars_source_soul_stone_damage = 1.0
	#魔源魂石最大魔源
	#Range: 0.0 ~ 2.147483647E9
	ars_source_soul_stone_mana = 30.0
	#魔源魂石魔源再生
	#Range: 0.0 ~ 2.147483647E9
	ars_source_soul_stone_re = 1.0
	#梦幻学派魂石法术增幅
	#Range: 0.0 ~ 2.147483647E9
	fantasy_sect_soul_stone_damage = 0.2
	#梦幻学派魂石梦终抗性
	#Range: 0.0 ~ 2.147483647E9
	fantasy_sect_soul_stone_fantasy_ending_damage_resistance = 0.17
	#梦幻学派魂石梦终伤害
	#Range: 0.0 ~ 2.147483647E9
	fantasy_sect_soul_stone_fantasy_ending_damage = 3.0
	#梦幻学派魂石梦影抗性
	#Range: 0.0 ~ 2.147483647E9
	fantasy_sect_soul_stone_dream_shadow_damage_resistance = 0.15
	#梦幻学派魂石梦影伤害
	#Range: 0.0 ~ 2.147483647E9
	fantasy_sect_soul_stone_dream_shadow_damage = 4.0
	#梦幻学派魂石梦幻法强
	#Range: 0.0 ~ 2.147483647E9
	fantasy_sect_soul_stone_fantacy_power = 0.275
	#梦幻学派魂石通用法强
	#Range: 0.0 ~ 2.147483647E9
	fantasy_sect_soul_stone_power = 0.2
	#岩土学派魂石法强
	#Range: 0.0 ~ 2.147483647E9
	earth_sect_soul_stone_power = 0.1
	#岩土学派魂石buff时间
	#Range: 0.0 ~ 2.147483647E9
	earth_sect_soul_stone_time = 5.0
	#岩土学派魂石buff提升概率
	#Range: 0.0 ~ 2.147483647E9
	earth_sect_soul_stone_chance = 0.3
	#岩土学派魂石最高buff提升等级
	#Range: 0.0 ~ 2.147483647E9
	earth_sect_soul_stone_level = 10.0
	#律灵学派魂石随从减伤
	#Range: 0.0 ~ 2.147483647E9
	sound_sect_soul_stone_armor = 0.5
	#律灵学派魂石自身增伤
	#Range: 0.0 ~ 2.147483647E9
	sound_sect_soul_stone_owner_damage = 0.05
	#律灵学派魂石随从增伤
	#Range: 0.0 ~ 2.147483647E9
	sound_sect_soul_stone_damage = 0.25
	#律灵学派魂石法强
	#Range: 0.0 ~ 2.147483647E9
	sound_sect_soul_stone_power = 0.1
	#源流学派魂石法强
	#Range: 0.0 ~ 2.147483647E9
	aqua_sect_soul_stone_power = 0.1
	#源流学派魂石buff时间
	#Range: 0.0 ~ 2.147483647E9
	aqua_sect_soul_stone_time = 5.0
	#源流学派魂石buff提升概率
	#Range: 0.0 ~ 2.147483647E9
	aqua_sect_soul_stone_chance = 0.3
	#源流学派魂石最高buff提升等级
	#Range: 0.0 ~ 2.147483647E9
	aqua_sect_soul_stone_level = 10.0
	#邪术学派魂石伤害增幅
	#Range: 0.0 ~ 2.147483647E9
	eldritch_sect_soul_stone_damage = 0.075
	#邪术学派魂石抑影时间
	#Range: 0.0 ~ 2.147483647E9
	eldritch_sect_soul_stone_time = 10.0
	#邪术学派魂石法强
	#Range: 0.0 ~ 2.147483647E9
	eldritch_sect_soul_stone_power = 0.1
	#末影学派魂石伤害增幅
	#Range: 0.0 ~ 2.147483647E9
	ender_sect_soul_stone_damage = 0.1
	#末影学派魂石抑影时间
	#Range: 0.0 ~ 2.147483647E9
	ender_sect_soul_stone_time = 10.0
	#末影学派魂石法强
	#Range: 0.0 ~ 2.147483647E9
	ender_sect_soul_stone_power = 0.1
	#血腥学派魂石宠物吸血转化
	#Range: 0.0 ~ 2.147483647E9
	blood_sect_soul_stone_owner = 0.5
	#血腥学派魂石自身吸血
	#Range: 0.0 ~ 2.147483647E9
	blood_sect_soul_stone_heal = 0.15
	#血腥学派魂石法强
	#Range: 0.0 ~ 2.147483647E9
	blood_sect_soul_stone_power = 0.1
	#自然学派魂石法强
	#Range: 0.0 ~ 2.147483647E9
	nature_sect_soul_stone_power = 0.1
	#自然学派魂石buff增加时间
	#Range: 0.0 ~ 2.147483647E9
	nature_sect_soul_stone_time = 0.2
	#自然学派魂石buff提升概率
	#Range: 0.0 ~ 2.147483647E9
	nature_sect_soul_stone_chance = 0.3
	#自然学派魂石最高buff提升等级
	#Range: 0.0 ~ 2.147483647E9
	nature_sect_soul_stone_level = 15.0
	#唤魔学派魂石随从减伤
	#Range: 0.0 ~ 2.147483647E9
	evocation_sect_soul_stone_armor = 0.3
	#唤魔学派魂石自身增伤
	#Range: 0.0 ~ 2.147483647E9
	evocation_sect_soul_stone_owner_damage = 0.05
	#唤魔学派魂石随从增伤
	#Range: 0.0 ~ 2.147483647E9
	evocation_sect_soul_stone_damage = 0.15
	#唤魔学派魂石法强
	#Range: 0.0 ~ 2.147483647E9
	evocation_sect_soul_stone_power = 0.1
	#神圣学派魂石时长
	#Range: 0.0 ~ 2.147483647E9
	holy_sect_soul_stone_time = 10.0
	#神圣学派魂石伤害增幅
	#Range: 0.0 ~ 2.147483647E9
	holy_sect_soul_stone_damage = 0.1
	#神圣学派魂石法强
	#Range: 0.0 ~ 2.147483647E9
	holy_sect_soul_stone_power = 0.1
	#雷霆学派魂石最长超负荷时长
	#Range: 0.0 ~ 2.147483647E9
	lightning_sect_soul_stone_time = 10.0
	#雷霆学派魂石伤害转化比例
	#Range: 0.0 ~ 2.147483647E9
	lightning_sect_soul_stone_damage = 0.4
	#雷霆学派魂石雷霆法强
	#Range: 0.0 ~ 2.147483647E9
	lightning_sect_soul_stone_power = 0.1
	#冰霜学派魂石冰霜法强
	#Range: 0.0 ~ 2.147483647E9
	ice_sect_soul_stone_ice_power = 0.1
	#冰霜学派魂石冰封时间
	#Range: 0.0 ~ 2.147483647E9
	ice_sect_soul_stone_time = 10.0
	#冰霜学派魂石冰封增伤
	#Range: 0.0 ~ 2.147483647E9
	ice_sect_soul_stone_ice_damage = 0.1
	#炽焰学派魂石炽焰最大增幅
	#Range: 0.0 ~ 2.147483647E9
	fire_sect_soul_stone_fire_max_damage = 0.15
	#炽焰学派魂石炽焰最小增幅
	#Range: 0.0 ~ 2.147483647E9
	fire_sect_soul_stone_fire_min_damage = 0.05
	#炽焰学派魂石炽焰法强
	#Range: 0.0 ~ 2.147483647E9
	fire_sect_soul_stone_fire_power = 0.1
	#飞翼魂石飞行速度
	#Range: 0.0 ~ 2.147483647E9
	wing_soul_stone = 1.0
	#水生魂石水下增伤
	#Range: 0.0 ~ 2.147483647E9
	aquatic_soul_stone = 0.15
	#动物魂石额外战利品数量
	#Range: 0.0 ~ 2.147483647E9
	animal_soul_stone = 1.0
	#节肢增伤
	#Range: 0.0 ~ 2.147483647E9
	arthropod_soul_stone = 0.15
	#亡灵增伤
	#Range: 0.0 ~ 2.147483647E9
	death_soul_stone = 0.15
	#狱灵增伤
	#Range: 0.0 ~ 2.147483647E9
	blaze_soul_stone = 0.15
	#森林间隔
	#Range: 0.0 ~ 2.147483647E9
	forest_soul_stone = 3.0
	#自然饱和度
	#Range: 0.0 ~ 2.147483647E9
	lush_soul_stone_saturation = 1.0
	#自然饥饿度
	#Range: 0.0 ~ 2.147483647E9
	lush_soul_stone_food = 1.0
	#海洋游泳速度
	#Range: 0.0 ~ 2.147483647E9
	ocean_soul_stone = 0.5
	#末地-末影人特攻
	#Range: 0.0 ~ 2.147483647E9
	ender_soul_stone_attack = 0.5
	#末地-末影人特防
	#Range: 0.0 ~ 2.147483647E9
	ender_soul_stone_armor = 0.4
	#蘑菇魂石概率
	#Range: 0.0 ~ 2.147483647E9
	mushroom_soul_stone = 0.5
	#下界魂石增伤
	#Range: 0.0 ~ 2.147483647E9
	nether_soul_stone = 0.15
	#下界合金魂石击退抗性
	#Range: 0.0 ~ 2.147483647E9
	netherite_soul_stone = 0.4
	#下界合金魂石护甲韧性
	#Range: 0.0 ~ 2.147483647E9
	netherite_soul_stone_armor = 3.0
	#煤炭魂石移速
	#Range: 0.0 ~ 2.147483647E9
	coal_soul_stone = 0.2
	#铜魂石挖掘速度
	#Range: 0.0 ~ 2.147483647E9
	copper_soul_stone = 0.5
	#绿宝石魂石声望
	#Range: 0.0 ~ 2.147483647E9
	emerald_soul_stone = 100.0
	#红石攻击速度
	#Range: 0.0 ~ 2.147483647E9
	redstone_soul_stone = 0.25
	#铁魂石护甲值
	#Range: 0.0 ~ 2.147483647E9
	iron_soul_stone = 5.0
	#金魂石附魔等级
	#Range: 0.0 ~ 2.147483647E9
	gold_soul_stone = 5.0
	#钻石魂石抢夺
	#Range: 0.0 ~ 100.0
	diamond_soul_stone_looting = 2.0
	#钻石魂石时运
	#Range: 0.0 ~ 100.0
	diamond_soul_stone_fortune = 2.0
	#青金石经验倍率
	#Range: 0.0 ~ 100.0
	lapis_lazuli_soul_stone = 1.0
	#斯库拉魂石潮湿增伤
	#Range: 0.0 ~ 2.147483647E9
	scylla_soul_stone_damage = 0.1
	#斯库拉魂石潮湿等级
	#Range: 0.0 ~ 2.147483647E9
	scylla_soul_stone_level = 1.0
	#斯库拉魂石潮湿时间
	#Range: 0.0 ~ 2.147483647E9
	scylla_soul_stone_time = 10.0
	#下界合金巨兽最大等级
	#Range: 0.0 ~ 2.147483647E9
	netherite_monstrosity_soul_stone_max_lvl = 3.0
	#下界合金巨兽魂石BUFF时长
	#Range: 0.0 ~ 2.147483647E9
	netherite_monstrosity_soul_stone_time = 10.0
	#下界合金巨兽魂石概率
	#Range: 0.0 ~ 2.147483647E9
	netherite_monstrosity_soul_stone_chance = 0.2
	#先驱者魂石无敌时间削减
	#Range: 0.0 ~ 2.147483647E9
	the_harbinger_soul_stone = 0.5
	#远古遗魂魂石骨裂等级
	#Range: 0.0 ~ 2.147483647E9
	ancient_remnant_soul_stone_lvl = 1.0
	#远古遗魂魂石骨裂时间
	#Range: 0.0 ~ 2.147483647E9
	ancient_remnant_soul_stone_time = 5.0
	#远古遗魂魂石护甲韧性
	#Range: 0.0 ~ 2.147483647E9
	ancient_remnant_soul_stone_armor = 3.0
	#末影守卫魂石时间
	#Range: 0.0 ~ 2.147483647E9
	ender_guardian_soul_stone_time = 2.0
	#末影守卫魂石概率
	#Range: 0.0 ~ 2.147483647E9
	ender_guardian_soul_stone_chance = 0.25
	#咒翼灵骸魂石冷却时间
	#Range: 0.0 ~ 2.147483647E9
	maledictus_soul_stone_cooldown_time = 300.0
	#咒翼灵骸魂石防火时间
	#Range: 0.0 ~ 2.147483647E9
	maledictus_soul_stone_fire_time = 10.0
	#咒翼灵骸魂石复活无敌
	#Range: 0.0 ~ 2.147483647E9
	maledictus_soul_stone_time = 5.0
	#咒翼灵骸魂石复活治疗量
	#Range: 0.0 ~ 2.147483647E9
	maledictus_soul_stone_heal = 0.2
	#咒翼灵骸魂石弹射物免伤额外概率
	#Range: 0.0 ~ 2.147483647E9
	maledictus_soul_stone_arrow_chance = 0.15
	#咒翼灵骸魂石免伤概率
	#Range: 0.0 ~ 2.147483647E9
	maledictus_soul_stone_chance = 0.05
	#焰魔魂石水下增伤
	#Range: 0.0 ~ 2.147483647E9
	the_leviathan_soul_stone_damage = 0.1
	#焰魔魂石水上减伤
	#Range: 0.0 ~ 2.147483647E9
	the_leviathan_soul_stone_armor = 0.2
	#利维坦魂石等级
	#Range: 0.0 ~ 2.147483647E9
	the_leviathan_soul_stone_level = 3.0
	#利维坦魂石时间
	#Range: 0.0 ~ 2.147483647E9
	the_leviathan_soul_stone_time = 5.0
	#焰魔魂石基础概率
	#Range: 0.0 ~ 2.147483647E9
	ignis_soul_stone_give_chance = 0.6
	#焰魔魂石等级时间
	#Range: 0.0 ~ 2.147483647E9
	ignis_soul_stone_time = 10.0
	#焰魔魂石等级提升概率
	#Range: 0.0 ~ 2.147483647E9
	ignis_soul_stone_up_chance = 0.3
	#焰魔魂石最高等级
	#Range: 0.0 ~ 2.147483647E9
	ignis_soul_stone_max_level = 5.0
	#机枪魂石增伤
	#Range: 0.0 ~ 2.147483647E9
	machine_gun_soul_stone = 0.10000000149011612
	#重型枪械魂石概率
	#Range: 0.0 ~ 2.147483647E9
	heavy_machine_gun_soul_stone = 0.5
	#冲锋枪魂石概率
	#Range: 0.0 ~ 2.147483647E9
	submachine_gun_soul_stone_chance = 0.25
	#冲锋枪魂石移速
	#Range: 0.0 ~ 2.147483647E9
	submachine_gun_soul_stone_speed = 0.10000000149011612
	#霰弹枪魂石破甲
	#Range: 0.0 ~ 2.147483647E9
	shotgun_soul_stone = 0.25
	#狙击枪魂石最高增伤
	#Range: 0.0 ~ 2.147483647E9
	sniper_rifle_soul_stone_damage = 0.3
	#狙击枪魂石最长间隔
	#Range: 0.0 ~ 2.147483647E9
	sniper_rifle_soul_stone_time = 3.0
	#步枪魂石最长间隔
	#Range: 0.0 ~ 2.147483647E9
	rifle_soul_stone_time = 5.0
	#步枪魂石最高增伤
	#Range: 0.0 ~ 2.147483647E9
	rifle_soul_stone_damage = 0.15
	#步枪魂石最高连射次数
	#Range: 0.0 ~ 2.147483647E9
	rifle_soul_stone_number = 10.0
	#手枪魂石爆头伤害
	#Range: 0.0 ~ 2.147483647E9
	handgun_soul_stone = 0.5
	#弹药魂石弹药数
	#Range: 1.0 ~ 2.147483647E9
	ammo_soul_stone_number = 1.0
	#弹药魂石间隔
	#Range: 0.05 ~ 2.147483647E9
	ammo_soul_stone_time = 5.0
	#泰拉钢魂石是否允许左键释放光束
	terrasteel_soul_stone_left = true
	#泰拉钢魂石魔力恢复数额
	#Range: 0.0 ~ 2.147483647E9
	terrasteel_soul_stone_mana = 20.0
	#精灵钢魂石DEBUFF时长
	#Range: 0.0 ~ 2.147483647E9
	elementium_soul_stone_time = 3.0
	#精灵钢魂石攻击力基础
	#Range: 0.0 ~ 2.147483647E9
	elementium_soul_stone_atk = 0.5
	#精灵钢魂石概率
	#Range: 0.0 ~ 2.147483647E9
	elementium_soul_stone_chance = 0.5
	#魔力钢魂石耐久回复数额
	#Range: 0.0 ~ 2.147483647E9
	manasteel_soul_stone_number = 1.0
	#魔力钢魂石消耗
	#Range: 0.0 ~ 2.147483647E9
	manasteel_soul_stone_mana = 70.0
	#魔力钢魂石间隔
	#Range: 0.05 ~ 2.147483647E9
	manasteel_soul_stone_time = 2.0
	#盖亚魂石回血数额
	#Range: 0.0 ~ 2.147483647E9
	gaia_soul_stone_heal = 1.0
	#盖亚魂石回血间隔
	#Range: 0.05 ~ 2.147483647E9
	gaia_soul_stone_time = 2.0
	#盖亚魂石暴击伤害
	#Range: 0.0 ~ 2.147483647E9
	gaia_soul_stone_damage = 1.5
	#盖亚魂石暴击概率
	#Range: 0.0 ~ 2.147483647E9
	gaia_soul_stone_chance = 0.5
	#迷题羊魂石减伤
	#Range: 0.0 ~ 2.147483647E9
	quest_ram_soul_stone = 0.15
	#巨人魂石实体距离
	#Range: 0.0 ~ 2.147483647E9
	twilight_giant_soul_stone_block = 2.5
	#巨人魂石实体距离
	#Range: 0.0 ~ 2.147483647E9
	twilight_giant_soul_stone_entity = 2.5
	#浮云魂石减伤
	#Range: 0.0 ~ 2.147483647E9
	fluffy_cloud_soul_stone = 0.15
	#炽铁魂石回血比例
	#Range: 0.0 ~ 2.147483647E9
	fiery_iron_soul_stone_heal = 0.1
	#炽铁魂石燃烧时长
	#Range: 0.0 ~ 2.147483647E9
	fiery_iron_soul_stone_time = 10.0
	#钢叶魂石数额
	#Range: 0.0 ~ 2.147483647E9
	steeleaf_soul_stone_number = 1.0
	#钢叶魂石间隔
	#Range: 0.0 ~ 2.147483647E9
	steeleaf_soul_stone_time = 3.0
	#铁木魂石护甲韧性
	#Range: 0.0 ~ 2.147483647E9
	ironwood_soul_stone_armor_toughness = 1.0
	#铁木魂石护甲
	#Range: 0.0 ~ 2.147483647E9
	ironwood_soul_stone_armor = 3.0
	#梦幻学派魂石外学派转化率
	#Range: 0.0 ~ 2.147483647E9
	fantacy_sect_soul_stone_other = 0.3
	#岩土学派魂石外学派转化率
	#Range: 0.0 ~ 2.147483647E9
	earth_sect_soul_stone_other = 0.3
	#律灵学派魂石外学派转化率
	#Range: 0.0 ~ 2.147483647E9
	sound_sect_soul_stone_other = 0.3
	#源流学派魂石外学派转化率
	#Range: 0.0 ~ 2.147483647E9
	aqua_sect_soul_stone_other = 0.3
	#邪术学派魂石外学派转化率
	#Range: 0.0 ~ 2.147483647E9
	eldritch_sect_soul_stone_other = 0.3
	#末影学派魂石外学派转化率
	#Range: 0.0 ~ 2.147483647E9
	ender_sect_soul_stone_other = 0.3
	#自然学派魂石外学派转化率
	#Range: 0.0 ~ 2.147483647E9
	nature_sect_soul_stone_other = 0.3
	#猩红学派魂石外学派转化率
	#Range: 0.0 ~ 2.147483647E9
	blood_sect_soul_stone_other = 0.3
	#神圣学派魂石外学派转化率
	#Range: 0.0 ~ 2.147483647E9
	holy_sect_soul_stone_other = 0.3
	#唤魔学派魂石外学派转化率
	#Range: 0.0 ~ 2.147483647E9
	evocation_sect_soul_stone_other = 0.3
	#雷霆学派魂石外学派转化率
	#Range: 0.0 ~ 2.147483647E9
	lightning_sect_soul_stone_other = 0.3
	#冰霜学派魂石外学派转化率
	#Range: 0.0 ~ 2.147483647E9
	ice_sect_soul_stone_other = 0.3
	#炽焰学派魂石外学派转化率
	#Range: 0.0 ~ 2.147483647E9
	fire_sect_soul_stone_other = 0.3
	#娜迦魂石治疗增幅
	#Range: 0.0 ~ 2.147483647E9
	naga_soul_stone_heal = 0.2
	#娜迦魂石移速
	#Range: 0.0 ~ 2.147483647E9
	naga_soul_stone_speed = 0.1
	#冰雪女王魂石冷却
	#Range: 0.0 ~ 2.147483647E9
	snow_queen_soul_stone_cooldown = 0.2
	#冰雪女王魂石伤害
	#Range: 0.0 ~ 2.147483647E9
	snow_queen_soul_stone_damage = 0.25
	#冰雪女王魂石范围
	#Range: 0.0 ~ 2.147483647E9
	snow_queen_soul_stone_range = 9.0
	#雪怪魂石冷却
	#Range: 0.0 ~ 2.147483647E9
	alpha_yeti_soul_stone_cooldown = 0.2
	#雪怪魂石伤害
	#Range: 0.0 ~ 2.147483647E9
	alpha_yeti_soul_stone_damage = 0.15
	#雪怪魂石范围
	#Range: 0.0 ~ 2.147483647E9
	alpha_yeti_soul_stone_range = 7.0
	#雪怪魂石HP
	#Range: 0.0 ~ 2.147483647E9
	alpha_yeti_soul_stone_hp = 0.05
	#暮初恶魂魂石减伤
	#Range: 0.0 ~ 2.147483647E9
	ur_ghast_soul_stone_armor = 0.2
	#暮初恶魂魂石减伤时长
	#Range: 0.0 ~ 2.147483647E9
	ur_ghast_soul_stone_time = 2.0
	#暮初恶魂魂石护甲穿透
	#Range: 0.0 ~ 2.147483647E9
	ur_ghast_soul_stone_number = 0.072
	#米诺菇魂石护甲穿透
	#Range: 0.0 ~ 2.147483647E9
	minoshroom_soul_stone = 0.2
	#幻影骑士魂石护甲增伤
	#Range: 0.0 ~ 2.147483647E9
	knight_phantom_soul_stone_damage = 0.15
	#幻影骑士魂石护甲阈值
	#Range: 0.0 ~ 2.147483647E9
	knight_phantom_soul_stone_armor = 0.0
	#九头蛇魂石最高增伤
	#Range: 0.0 ~ 2.147483647E9
	twilight_hydra_soul_stone_damage = 0.3
	#九头蛇魂石最多回血
	#Range: 0.0 ~ 2.147483647E9
	twilight_hydra_soul_stone_heal = 1.0
	#九头蛇魂石生命阈值
	#Range: 0.0 ~ 2.147483647E9
	twilight_hydra_soul_stone_last_hp = 0.1
	#九头蛇魂石减伤数额
	#Range: 0.0 ~ 2.147483647E9
	twilight_hydra_soul_stone_armor = 0.5
	#九头蛇魂石减伤范围
	#Range: 0.0 ~ 2.147483647E9
	twilight_hydra_soul_stone_range = 21.0
	#光巫魂石僵尸冷却时间
	#Range: 0.0 ~ 2.147483647E9
	fortification_soul_stone_cooldown = 60.0
	#血巫魂石伤害饱和转换比例
	#Range: 0.0 ~ 2.147483647E9
	lifedrain_soul_stone_sat = 0.05
	#血巫魂石伤害饥饿转换比例
	#Range: 0.0 ~ 2.147483647E9
	lifedrain_soul_stone_food = 0.05
	#血巫魂石伤害回血转换比例
	#Range: 0.0 ~ 2.147483647E9
	lifedrain_soul_stone_heal = 0.05
	#尸巫魂石僵尸召唤间隔时间
	#Range: 0.0 ~ 2.147483647E9
	zombie_scepter_soul_stone_cooldown = 10.0
	#尸巫魂石僵尸BUFF时间
	#Range: 0.0 ~ 2.147483647E9
	zombie_scepter_soul_stone_time = 30.0
	#尸巫魂石僵尸生命提升等级
	#Range: 0.0 ~ 255.0
	zombie_scepter_soul_stone_hp_boost = 1.0
	#尸巫魂石僵尸力量等级
	#Range: 0.0 ~ 255.0
	zombie_scepter_soul_stone_strength = 1.0
	#玫瑰石英魂石耐久回复
	#Range: 0.0 ~ 2.147483647E9
	rose_quartz_soul_stone_number = 1.0
	#玫瑰石英魂石头盔能力
	rose_quartz_soul_stone_heat = true
	#烈焰蛋糕魂石燃烧时间
	#Range: 0.0 ~ 2.147483647E9
	blaze_cake_soul_stone_time = 60.0
	#烈焰蛋糕魂石最高燃烧时间
	#Range: 0.0 ~ 2.147483647E9
	blaze_cake_soul_stone_max_time = 180.0
	#烈焰蛋糕魂石右键时是否是超级燃烧(目前无法进行超级燃烧，所以只能正常燃起来)
	blaze_cake_soul_stone_super = false
	#纸板魂石功能
	cardboard_soul_stone = true
	#坚固板魂石机器伤害减免
	#Range: 0.0 ~ 2.147483647E9
	sturdy_sheet_soul_stone_damage = 1.0
	#黄铜魂石机器伤害减免
	#Range: 0.0 ~ 2.147483647E9
	brass_soul_stone_damage = 0.9
	#安山合金魂石潜水靴功能
	andesite_alloy_soul_stone_boot = true
	#安山合金魂石护目镜功能
	andesite_alloy_soul_stone_eyes = true
	#锌魂石是否可以不消耗饥饿度使用曲柄
	zinc_soul_stone_use = true
	#锌魂石挖掘速度
	#Range: 0.0 ~ 2.147483647E9
	zinc_soul_stone_speed = 0.5
	#蔓生巨像魂石等级
	#Range: 0.0 ~ 2.147483647E9
	overgrown_colossus_soul_stone_level = 1.0
	#蔓生巨像魂石时长
	#Range: 0.0 ~ 2.147483647E9
	overgrown_colossus_soul_stone_time = 5.0
	#潜影拟态者魂石冷却
	#Range: 0.0 ~ 2.147483647E9
	shulker_mimic_soul_stone_cooldown = 4.0
	#潜影拟态者魂石等级
	#Range: 0.0 ~ 2.147483647E9
	shulker_mimic_soul_stone_level = 1.0
	#潜影拟态者魂石时长
	#Range: 0.0 ~ 2.147483647E9
	shulker_mimic_soul_stone_time = 3.0
	#潜影拟态者魂石几率
	#Range: 0.0 ~ 2.147483647E9
	shulker_mimic_soul_stone_chance = 0.3
	#末影遣使魂石减伤
	#Range: 0.0 ~ 2.147483647E9
	endersent_soul_stone = 0.25
	#沙丘哨兵魂石减伤
	#Range: 0.0 ~ 2.147483647E9
	dune_sentinel_soul_stone_down = 0.25
	#沙丘哨兵魂石增伤
	#Range: 0.0 ~ 2.147483647E9
	dune_sentinel_soul_stone_up = 0.15
	#魄攫圣骑魂石等级
	#Range: 0.0 ~ 2.147483647E9
	posessed_paladin_soul_stone_level = 1.0
	#魄攫圣骑魂石范围
	#Range: 0.0 ~ 2.147483647E9
	posessed_paladin_soul_stone_range = 21.0
	#魄攫圣骑魂石时间
	#Range: 0.0 ~ 2.147483647E9
	posessed_paladin_soul_stone_time = 3.0
	#魄攫圣骑魂石几率
	#Range: 0.0 ~ 2.147483647E9
	posessed_paladin_soul_stone_chance = 0.5
	#荒古守卫者魂石护甲提升数额
	#Range: 0.0 ~ 2.147483647E9
	ancient_guardian_soul_stone_armor = 0.25
	#荒古守卫者魂石护甲提升阈值
	#Range: 0.0 ~ 2.147483647E9
	ancient_guardian_soul_stone_hp = 0.5
	#荒古守卫者魂石冷却
	#Range: 0.0 ~ 2.147483647E9
	ancient_guardian_soul_stone_cooldown = 0.2
	#荒古守卫者魂石BUFF时间
	#Range: 0.0 ~ 2.147483647E9
	ancient_guardian_soul_stone_time = 3.0
	#荒古守卫者魂石概率
	#Range: 0.0 ~ 2.147483647E9
	ancient_guardian_soul_stone_chance = 0.5
	#荒古守卫者魂石百分比伤害
	#Range: 0.0 ~ 2.147483647E9
	ancient_guardian_soul_stone_damage = 0.25
	#荒古守卫者魂石固定伤害
	#Range: 0.0 ~ 2.147483647E9
	ancient_guardian_soul_stone_fixed_damage = 5.0
	#霜冻傀儡魂石冷却
	#Range: 0.0 ~ 2.147483647E9
	frostbitten_golem_soul_stone_cooldown = 0.2
	#霜冻傀儡魂石等级
	#Range: 0.0 ~ 2.147483647E9
	frostbitten_golem_soul_stone_level = 1.0
	#霜冻傀儡魂石时长
	#Range: 0.0 ~ 2.147483647E9
	frostbitten_golem_soul_stone_time = 3.0
	#霜冻傀儡魂石伤害
	#Range: 0.0 ~ 2.147483647E9
	frostbitten_golem_soul_stone_damage = 0.2
	#霜冻傀儡魂石范围
	#Range: 0.0 ~ 2.147483647E9
	frostbitten_golem_soul_stone_range = 7.0
	#湫渃云魔魂石无敌时间延长
	#Range: 0.0 ~ 2.147483647E9
	cloud_golem_soul_stone_time = 0.5
	#湫渃云魔魂石冷却
	#Range: 0.0 ~ 2.147483647E9
	cloud_golem_soul_stone_cooldown = 0.2
	#湫渃云魔魂石雷伤
	#Range: 0.0 ~ 2.147483647E9
	cloud_golem_soul_stone_damage = 0.35
	#熔岩食者魂石燃烧时长
	#Range: 0.0 ~ 2.147483647E9
	lava_eater_soul_stone_time = 5.0
	#凋灵恶煞魂石凋零等级
	#Range: 0.0 ~ 2.147483647E9
	withered_abomination_soul_stone_level = 1.0
	#凋灵恶煞魂石凋零时长
	#Range: 0.0 ~ 2.147483647E9
	withered_abomination_soul_stone_time = 5.0
	#凋灵恶煞魂石攻击
	#Range: 0.0 ~ 2.147483647E9
	withered_abomination_soul_stone_atk = 0.125
	#骷髅蜥龙魂石击退抗性
	#Range: 0.0 ~ 2.147483647E9
	skeletosaurus_soul_stone_knockback_resistance = 0.2
	#骷髅蜥龙魂石护甲
	#Range: 0.0 ~ 2.147483647E9
	skeletosaurus_soul_stone_armor = 2.0
	#骷髅蜥龙魂石攻击
	#Range: 0.0 ~ 2.147483647E9
	skeletosaurus_soul_stone_atk = 0.075
	#末影守卫魂石冷却
	#Range: 0.0 ~ 2.147483647E9
	ender_guardian_soul_stone_cooldown = 5.0

