
["Mob Configs"]
	#Whether players can remove the saddle and chests of a Carrybug with shears
	CanRemoveCarrybugSaddle = true
	#Determines how many babies a Bunbug will give birth to
	BunbugBirthNumber = 4.0
	#Whether Snowflake Spiders inflict Frostbite when attacking
	SnowflakeSpiderInflictFrostbite = true
	#How much does Bouncelizard bounce
	BouncelizardRegularJumpHeight = 0.6
	#How much does a sleeping Bouncelizard bounce
	BouncelizardSleepingJumpHeight = 1.2
	#1 out of this number chance for a warm biome monster to spawn with Blossoming effect
	CreeblossomInfectionRate = 30.0
	#Whether Warptraps attack Endermen
	WarptrapAttackEndermen = true
	#Whether Shimmerwings follow players with End's Blessing effect
	ShimmerwingFollowBlessedPlayer = true
	#Whether Balloon Rat poisons attackers
	BalloonRatPoisonsTarget = true
	#Whether Bomb Jellies should have animated textures
	AnimateBombJelly = true
	#How big is the explosion of a Small Bomb Jelly
	SmallBombJellyExplosionPower = 2.0
	#How big is the explosion of a Medium Bomb Jelly
	MediumBombJellyExplosionPower = 3.0
	#How big is the explosion of a Large Bomb Jelly
	LargeBombJellyExplosionPower = 4.0
	#1 out of this number chance for an iropod to be black
	BlackIropodChance = 100.0
	#Whether Shadelet can jumpscare players
	CanShadeletJumpscarePlayer = true
	#1 out of this number chance for an enderman in the end to spawn with Endfected effect
	NervoidInfectionRate = 50.0
	#How long will Corpse Quartermaster wait before healing
	QuartermasterHealCooldown = 150.0
	#How long will Corpse Captain wait before summoning backup
	CaptainSummonCooldown = 600.0
	#How long will Corpse Tank wait before shooting
	TankShootCooldown = 200.0

["Item Configs"]
	#Mobs with this number or lower max health will be webbed when hit by a Web Sack
	WebbedRequirement = 50.0

["Block Configs"]
	#Whether Freezing Cobwebs Freeze mobs in it
	FreezingCobwebFreeze = true

