
[general]
	#Colors must be specified in #RRGGBB format
	"color values" = ["#FFFFFF", "#FF5500", "#FFC747", "#27FFE3", "#00FF00", "#7F00FF", "#FF0066", "FFFF00", "FF0000", "7D7D7D"]
	#Always show armor bar even if empty?
	"Always show bar" = false
	#Show empty armor icons?
	"Show empty icons" = false

