#A list of items to log on common setup.
items = ["minecraft:iron_ingot"]
#Wearing position: LEFT, CENTER, RIGHT
emblemPosition = "RIGHT"
#depth (0.0-1.0, The lower the value, the closer it is to the body)
#Range: 0.0 ~ 1.0
emblemDepth = 0.1
#emblem scale (0.1-2.0)
#Range: 0.1 ~ 2.0
emblemScale = 0.25

