
[avaritia]
	#Probability of a neutron pile is dropped by condensing modifier
	condensingDropProbability = 0.003

[mekanism]
	#Allow Mekaplate can use shield of electricity
	mekaplateUseShield = true

[apotheosis]
	#Maximum level of enchantments granted by override
	overrideLevelLimit = 255

#Provided by AddonAPI:
#Other Mod Compat Options
[compat]
	"SlashBlade Compat" = true
	"Create Compat" = true
	"Mekanism Compat" = true
	"Draconic Evolution Compat" = true
	"Avaritia Compat" = true
	"Apotheosis Compat" = true
	"TaCz Compat" = true
	"Iron's Spells n' Spellbooks Compat" = true
	"Curios API Compat" = true
	"Psi Compat" = true
	"ProjectE Compat" = true
	"CC:Tweaked Compat" = true
	"TiCEX Original Materials and Modifiers" = true
	"Botania Compat" = true
	"Ars Nouveau Compat" = true
	"JEI Compat" = true
	"TiCEX Original Utilities" = true
	Default = true

#General
[general]
	#Using ticex-more-config.toml(If true, it will override your datapack!)
	useMoreConfig = false
	#MAX Rate Capacity(RF/t)
	rateCapacity = 100000
	#Fluid Transmuter valid tag prefix list
	fluid_transmuter_patterns = ["forge:"]
	#Fluid Transmuter invalid tag prefix list
	fluid_transmuter_exclude_patterns = ["forge:water", "forge:lava"]

["ars nouveau"]
	#Internal cooldown ticks of spellcasting
	reactiveCooldown = 10

[curios]
	#Ticks remaining on the gauntlet after a gauntlet shot hits
	gantletRemainTicks = 40
	#Blacklist of entities that do not drop the glove.
	gloveDropBlacklist = ["minecraft:armor_stand", "dummmmmmy:target_dummy"]
	#Use gloveDropBlacklist as whitelist
	gloveDropBlacklistAsWhitelist = false

