
#RFFurnace Settings
[rf_furnace]
	#MAX Rate Capacity(RF/t)
	rateCapacity = 100000

[avaritia]
	#Probability of a neutron pile is dropped by condensing modifier
	condensingDropProbability = 0.003

[mekanism]
	#Allow Mekaplate can use shield of electricity
	mekaplateUseShield = true

[apotheosis]
	#Maximum level of enchantments granted by override
	overrideLevelLimit = 255

#Provided by AddonAPI:
#Other Mod Compat Options
[compat]
	"SlashBlade Compat" = true
	"Create Compat" = true
	"Mekanism Compat" = true
	"Sakura Tinker Compat" = true
	"Draconic Evolution Compat" = true
	"Tinkers' Things Compat" = true
	"Avaritia Compat" = true
	"Apotheosis Compat" = true
	"TaCz Compat" = true
	"Iron's Spells n' Spellbooks Compat" = true
	"Curios API Compat" = true

