
#***注意！
#***Notice
#这些配置并不会同步修改语言文件中的描述，当你修改了某个工具/工具属性的性质后如果想要更改描述则需要手动覆盖语言文件！
#This configure won't affect language display. When a certain modifier or tool is configured, please manually replace the description of the relating language contents.
#Tool Behaviour
#工具行为
[tool_behaviour]
	#Matter Manipulator behaviour
	#物质操纵器
	#Base mining speed multiplier of Matter Manipulator, 1.0 by default.
	#物质操纵器的定性挖掘效率倍率，默认1.0x。
	#Range: 0.0 ~ 2.147483647E9
	matter_manipulator_base_multiplier = 1.0
	#Base mining speed multiplier of Matter Manipulator when is conducting AOE mining, 0.5 by default.
	#物质操纵器进行范围挖掘时的定性挖掘效率倍率，默认0.5x。
	#Range: 0.0 ~ 2.147483647E9
	matter_manipulator_aoe_base_multiplier = 0.5
	#Mining fluid bonus multiplier of Matter Manipulator , 0.5 by default , meaning that each 200 °C adds 1 mining speed.
	#流体温度对物质操纵器挖掘速度的定量效率增幅。默认0.5x，意味着挖掘液每200℃增加1挖掘速度。
	#Range: 0.0 ~ 2.147483647E9
	matter_manipulator_fluid_bonus_multiplier = 0.5
	#Allows Matter Manipulator to gain enchantment boost from fluids in mining mode (e.g. Gain silk touch from molten emerald). true by default.
	#允许挖掘模式下的物质操纵器从流体效果中获得附魔等级（比如熔融钻石的时运III），默认true。
	matter_manipulator_fluid_enchanting = true
	#Base mining range for Matter Manipulator, 16.0 by default.
	#物质操纵器的基础挖掘距离，默认16.0格。
	#Range: 0.0 ~ 64.0
	matter_manipulator_base_range = 16.0
	#Capacity factor for Matter Manipulator, 10.0 by default.
	#物质操纵器的流体容量倍率，默认10.0x。
	#Range: 0.0 ~ 2.147483647E9
	matter_manipulator_base_capacity_factor = 10.0
	#Base fluid efficiency for Matter Manipulator, 1.0 by default.
	#物质操纵器的基础流体效率，默认0.0。
	#Range: 0.0 ~ 2.147483647E9
	matter_manipulator_base_fluid_efficiency = 0.0
	#Cancel the movement punishment when using Matter Manipulator,true by default.
	#取消物质操纵器使用时的移速惩罚，默认是。
	matter_manipulator_cancel_slowdown = true
	#Ionized Cannon behaviour
	#等离子射线炮
	#The multiplier of fluid consumption of Ionized Cannon, 1.0 by default.
	#等离子射线炮的定性流体消耗倍率，默认1.0x。
	#Range: 0.0 ~ 3.4028234663852886E38
	ionized_cannon_fluid_factor = 1.0
	#Damage multiplier for Ionized Cannon when using correct fluids, 4.0 by default.
	#当有合适流体时等离子射线炮的伤害倍率，默认4.0x。
	#Range: 1.0 ~ 3.4028234663852886E38
	ionized_cannon_damage_bonus = 4.0
	#Base fluid efficiency for Ionized Cannon, 0.0 by default.
	#等离子射线炮的基础流体效率，默认0.0。
	#Range: 0.0 ~ 3.4028234663852886E38
	ionized_cannon_base_fluid_efficiency = 0.0
	#Base explosion scale efficiency for Ionized Cannon, 1.0 by default.
	#等离子射线炮的基础效果范围，默认1.0。
	#Range: 0.0 ~ 3.4028234663852886E38
	ionized_cannon_base_scale = 1.0
	#Base attack range for Ionized Cannon, 12.0 by default.
	#等离子射线炮的基础攻击距离，默认12.0格。
	#Range: 0.0 ~ 3.4028234663852886E38
	ionized_cannon_base_range = 12.0
	#Base duration for Ionized Cannon to charge, 40 ticks by default.
	#等离子射线炮的基础蓄力时间，默认40 ticks。最终蓄力时间会除以攻速。
	#Range: > 0
	ionized_cannon_base_duration = 40
	#Allow Ionized Cannon to gain pierce level form impaling modifier, true by default.
	#允许等离子射线炮根据穿透词条的等级增加射线穿透数量，默认是。
	ionize_cannon_pierce_from_impaling = true
	#等离子射线炮使用伤害性流体时造成的流体效果的等级倍率，默认0.25，会与射线炮的基础伤害相乘。
	#Range: 0.0 ~ 3.4028234663852886E38
	IonizedCannonMultiplierForDamagingFluidEffect = 0.25
	#等离子射线炮等离子爆炸的攻击范围定性倍率，默认4，表示其爆炸范围大致有贴图的4倍大，不会影响贴图的大小。虽然最大支持浮点数上限，但是我劝你别！
	#Range: 0.0 ~ 3.4028234663852886E38
	IonizedCannonExplosionRange = 4.0
	#Electron Tuner behaviour
	#环流电子调谐剑
	#The adjustable range of attack damage for Electron Tuner, 1.5 by default, meaning that the damage can be adjusted within the range of ±0.75 .Note that adjusting this without adjusting electron_tuner_attack_speed_range will greatly affect balance.
	#环流电子调谐剑的伤害调节范围。默认1.5，意味着滑动调节滑块最大能对伤害产生 1/1.75 x ~ 1.75 x 的变化。仅调节此项会极大影响平衡，请考虑和攻速范围一同调整。
	#Range: 0.0 ~ 3.4028234663852886E38
	electron_tuner_damage_range = 1.5
	#The adjustable range of attack damage for Electron Tuner, 1.0 by default, meaning that the damage can be adjusted within the range of ±0.5 .Note that adjusting this without adjusting electron_tuner_damage_range will greatly affect balance.
	#环流电子调谐剑的攻击速度调节范围。默认1.0，意味着滑动调节滑块最大能对攻速产生 1/1.5 x ~ 1.5 x 的变化。仅调节此项会极大影响平衡，请考虑和伤害范围一同调整。
	#Range: 0.0 ~ 3.4028234663852886E38
	electron_tuner_attack_speed_range = 1.0
	#Allow Electron Tuner to perform special attack , true by default.
	#允许环流电子调谐剑造成特殊攻击（比如剑形态的弧光），默认true。
	electron_tuner_special = true
	#The basic energy consumption when attacking for Electron Tuner, 250 by default.
	#环流电子调谐剑攻击的能耗，默认250FE。
	#Range: > 0
	electron_tuner_consumption = 250

#Generator Modules
#能量模块类强化
[generator_modules]
	#Basic FE/t for each level of Combustion Generator Module, 200 by default
	#燃烧室能量模块的基础每tick产能，默认200FE/t。
	#Range: > 0
	combustion_generator_generation = 200
	#Energy per burning time, affects the total FE generated by fuel item. 10 by default, in this case a single coal can produce 16.00 kFE.
	#燃料每tick燃烧时间带来的总产能，默认10FE。注：烧炼一个物品需要200 ticks，一个煤炭能烧8个物品也就是1600 ticks，这代表默认配置下一个煤炭能带来16.0kFE的总产能。
	#Range: > 0
	combustion_generator_total_factor = 10
	#Basic FE/t for each level of Overslime Generator Module, 250 by default
	#凝胶电化学能量模块的基础每tick产出，默认250FE/t
	#Range: > 0
	overslime_generator_generation = 250
	#Energy per overslime, 1000 by default.
	#每点黏液产生的能量，默认1kFE。
	#Range: > 0
	overslime_generator_total_factor = 1000
	#Basic FE/t for each level of Piezoelectric Effect modifier, 100 by default
	#压电效应的基础每tick产能，默认100FE/t。
	#Range: > 0
	piezoelectric_effect_generation = 100
	#Energy per damage each level, 10 by default.
	#每级每点伤害产生的能量，默认10FE。
	#Range: > 0
	piezoelectric_effect_generation_per_damage = 10
	#Basic FE/t for each level of Electric Food modifier, 100 by default
	#充电饱的基础每tick消耗，默认100FE/t。
	#Range: > 0
	electric_food_consumption = 100
	#Energy per food level, 25kFE by default.
	#充电饱恢复1饱食度需要的能量，默认25kFE。
	#Range: > 0
	electric_food_total_consumption = 25000
	#Bonus for Transition Catalyst each trait level, 25% by default.
	#过渡金属催化剂的增幅效果，默认25%。
	#Range: 0.0 ~ 3.4028234663852886E38
	transition_catalyst_bonus = 0.25
	#Bonus for Platinoid Catalyst each trait level, 25% by default.
	#铂族催化剂的增幅效果，默认25%。
	#Range: 0.0 ~ 3.4028234663852886E38
	platinoid_catalyst_bonus = 0.25
	#Basic FE/t for each level of Smeltery Generator modifier, 300 by default
	#冶炼炉能量模块基础的每tick能量产出。默认300 FE/t。
	#Range: > 0
	smeltery_generator_generation = 300
	#Energy per burning time, 10000 by default.
	#每tick燃烧时长带来的总能量产出。默认10kFE。
	#Range: > 0
	smeltery_generator_generation_for_time = 10000
	#Power multiplier for fuel temp, 0.001 by default , meaning that a 2000℃ fuel makes FE/t times 2.
	#燃料温度对产能速率的影响。默认0.001，意味着2000℃的燃料会带来2倍的产能速度。
	#Range: 0.0 ~ 3.4028234663852886E38
	smeltery_generator_temperature_multiplier = 0.001
	#Basic FE/t for each level of Compressed Air Generator modifier, 200 by default
	#气动能量模块基础的每tick能量产出，默认50FE/t。注：最终产能会乘以工具压力。
	#Range: > 0
	compressed_air_generator_generation = 50

