
#Everything to do with gameplay
[gameplay]
	#Set this to true to enable ancient tool part swapping.
	enableAncientToolPartSwapping = false
	#Set this to any integer between 5 and 20 to define the maximum sparks a tool can acquire.
	#Range: 5 ~ 20
	maxSparksAcquired = 8
	#Set this to any integer between 1 and 10 to multiply the experience acquired to obtain sparks when defeating mobs.
	#Range: 1 ~ 10
	acquireSparkExperienceMultiplier = 1
	#Set this to any integer between 10 and 500 to define the experience required to obtain the first spark.
	#Range: 10 ~ 500
	initialRequiredSparkExperience = 50
	#Set this to any decimal between 1 and 10 to multiply the experience required to upgrade.
	#Range: 1.0 ~ 10.0
	requiredSparkExperienceMultiplier = 1.5

