
["Villager Settings"]
	#Enable Veggies Delight villager trades
	enableVillagerTrades = true
	#Enable Veggies Delight Wandering Trader trades
	enableWanderingTrades = true

["Structure Settings"]
	#Enable Veggies Delight to add new village structures (disables all compat if false)
	generateVeggiesDelightStructures = true

	["Structure Settings"."Village Settings"]
		#Enable generation of Veggies Delight structures in Vanilla villages
		generateVanillaVillageStructures = true

	["Structure Settings"."Compat Settings"]
		#Enable generation of Veggies Delight structures in Atmospheric villages
		generateAtmosphericVillageStructures = true
		#Enable generation of Veggies Delight structures in Nature's Spirit villages
		generateNatureSpiritVillageStructures = true
		#Enable generation of Veggies Delight structures in Repurposed Structures villages
		generateRepurposedStructuresVillageStructures = true
		#Enable generation of Veggies Delight structures in Windswept villages
		generateWindsweptVillageStructures = true
		#Enable generation of Veggies Delight structures in Explorify's Dark Forest Settlement
		generateExplorifyStructures = true

["Worldgen Settings"]

	["Worldgen Settings"."Worldgen Settings"]
		#Chance of Bell Peppers generating in the world. (0 to disable, higher = rarer)
		#Range: 0 ~ 512
		chanceBellPeppers = 100
		#Chance of Broccoli generating in the world. (0 to disable, higher = rarer)
		#Range: 0 ~ 512
		chanceBroccoli = 120
		#Chance of Cauliflowers generating in the world. (0 to disable, higher = rarer)
		#Range: 0 ~ 512
		chanceCauliflowers = 120
		#Chance of Garlic generating in the world. (0 to disable, higher = rarer)
		#Range: 0 ~ 512
		chanceGarlic = 120
		#Chance of Sweet Potatoes generating in the world. (0 to disable, higher = rarer)
		#Range: 0 ~ 512
		chanceSweetPotatoes = 120
		#Chance of Turnips generating in the world. (0 to disable, higher = rarer)
		#Range: 0 ~ 512
		chanceTurnips = 20
		#Chance of Zucchinis generating in the world. (0 to disable, higher = rarer)
		#Range: 0 ~ 512
		chanceZucchinis = 100
		#Chance of Mature Dandelions generating in the world. (0 to disable, higher = rarer)
		#Range: 0 ~ 512
		chanceMatureDandelion = 130

