
#World generation options.
[World]
	#Should Nether Mithril Ore generate in the world?
	generateNetherMithrilOre = true
	#Should Mithril Ore generate in the world?
	generateMithrilOre = true
	#Should End Iridium Ore generate in the world?
	generateEndIridiumOre = true
	#Should Nether Platinum Ore generate in the world?
	generateNetherPlatinumOre = true

