
#─────────────────────────────────────────────────────────────────────────
# Anywhere that uses IDs, such as blocks, biomes, dimensions, and structures, also supports:
# • Tags (e.g. "#minecraft:is_underground")
# • Comma-separated lists (e.g. "minecraft:desert,#minecraft:is_badlands")
#     Applies the setting to all listed IDs. Can use tags, regular IDs, and negation interchangeably
# • Negation (e.g. "!minecraft:jungle_leaves")
#     Useful with lists/tags. Excludes the listed IDs from the setting
#     i.e. "#minecraft:leaves,!minecraft:jungle_leaves" (all leaves EXCEPT jungle leaves)
# Settings with "//v" will list elements vertically. Removing "//v" will list elements in one line
#─────────────────────────────────────────────────────────────────────────
[Dimensions]
	#─────────────────────────────────────────────────────────────────────────//v
	# Applies an offset to the world's temperature across an entire dimension
	# ├── Format: [["dimension_id", temperature, *units], [...], etc]
	# └── [* = optional]
	# • dimension_id: The ID of the dimension (e.g. "minecraft:the_nether")
	# • temperature: The temperature offset to apply to the dimension
	# • *units: The units of the temperature ("f", "c", or "mc"). Defaults to Minecraft units (mc))
	"Dimension Temperature Offsets" = [
	    ["minecraft:the_end", -0.1, "MC"],
	    ["minecraft:the_nether", 0.7, "MC"],
	    ["twilightforest:twilight_forest_type", 0.2],
	    ["aether:the_aether", 0.7]
	]
	#─────────────────────────────────────────────────────────────────────────//v
	# Defines the temperature of a dimension, overriding biome and elevation temperature
	# ├── Format: [["dimension_id", temperature, *units], [...], etc]
	# └── [* = optional]
	# • dimension_id: The ID of the dimension (e.g. "minecraft:the_nether")
	# • temperature: The temperature of the dimension
	# • *units: The units of the temperature ("f", "c", or "mc"). Defaults to Minecraft units (mc))
	"Dimension Temperatures" = []

[Biomes]
	#─────────────────────────────────────────────────────────────────────────//v
	# Applies an offset to the temperature of a biome
	# ├── Format: [["biome_id", lowTemp, highTemp, *units, *waterTemp], [...], etc]
	# └── [* = optional]
	# • biome_id: The ID of the biome (e.g. "minecraft:desert")
	# • lowTemp: The temperature offset at midnight
	# • highTemp: The temperature offset at noon
	# • *units: The units of the temperature ("f", "c", or "mc"). Defaults to Minecraft units (mc))
	# • *waterTemp: Offsets the temperature of water in the biome
	"Biome Temperature Offsets" = []
	#─────────────────────────────────────────────────────────────────────────//v
	# Defines the temperature of a biome, overriding the biome's default temperature
	# ├── Format: [["biome_id", lowTemp, highTemp, *units, *waterTemp], [...], etc]
	# └── [* = optional]
	# • biome_id: The ID of the biome (e.g. "minecraft:desert")
	# • lowTemp: The temperature of the biome at midnight
	# • highTemp: The temperature of the biome at noon
	# • *units: The units of the temperature ("f", "c", or "mc"). Defaults to Minecraft units (mc))
	# • *waterTemp: The temperature of water in the biome
	"Biome Temperatures" = [
	    ["byg:skyris_vale", 42.0, 68.0, "F"],
	    ["biomesoplenty:highland_moor", 54.0, 68.0, "F"],
	    ["biomesoplenty:pumpkin_patch", 57.0, 78.0, "F"],
	    ["byg:autumnal_forest", 60.0, 75.0, "F"],
	    ["byg:zelkova_forest", 44.0, 61.0, "F"],
	    ["environmental:marsh", 60.0, 80.0, "F"],
	    ["minecraft:savanna_plateau", 76.0, 98.0, "F"],
	    ["biomesoplenty:grassland", 58.0, 82.0, "F"],
	    ["biomesoplenty:prairie", 66.0, 82.0, "F"],
	    ["byg:dacite_ridges", 40.0, 65.0, "F"],
	    ["biomesoplenty:snowy_coniferous_forest", 28.0, 48.0, "F"],
	    ["biomesoplenty:fir_clearing", 56.0, 68.0, "F"],
	    ["minecraft:taiga", 44.0, 62.0, "F"],
	    ["biomesoplenty:orchard", 58.0, 78.0, "F"],
	    ["biomesoplenty:wetland", 63.0, 74.0, "F"],
	    ["minecraft:savanna", 70.0, 95.0, "F"],
	    ["biomesoplenty:wooded_wasteland", 78.0, 95.0, "F"],
	    ["byg:lush_stacks", 66.0, 75.0, "F"],
	    ["minecraft:swamp", 72.0, 84.0, "F"],
	    ["atmospheric:sparse_rainforest_basin", 62.0, 83.0, "F"],
	    ["biomesoplenty:spider_nest", 75.0, 75.0, "F"],
	    ["minecraft:frozen_peaks", 15.0, 33.0, "F"],
	    ["biomesoplenty:rocky_rainforest", 73.0, 86.0, "F"],
	    ["biomesoplenty:bayou", 67.0, 78.0, "F"],
	    ["biomesoplenty:volcano", 94.0, 120.0, "F"],
	    ["minecraft:old_growth_spruce_taiga", 48.0, 62.0, "F"],
	    ["minecraft:deep_dark", 63.0, 63.0, "F"],
	    ["atmospheric:rainforest", 68.0, 90.0, "F"],
	    ["minecraft:warm_ocean", 67.0, 76.0, "F"],
	    ["biomesoplenty:coniferous_forest", 44.0, 58.0, "F"],
	    ["biomesoplenty:highland", 57.0, 70.0, "F"],
	    ["biomesoplenty:fungal_jungle", 73.0, 86.0, "F"],
	    ["minecraft:windswept_forest", 48.0, 66.0, "F"],
	    ["biomesoplenty:field", 64.0, 85.0, "F"],
	    ["atmospheric:rocky_dunes", 55.0, 125.0, "F"],
	    ["byg:dead_sea", 72.0, 82.0, "F"],
	    ["biomesoplenty:dune_beach", 67.0, 78.0, "F"],
	    ["biomesoplenty:old_growth_woodland", 65.0, 78.0, "F"],
	    ["minecraft:stony_shore", 50.0, 64.0, "F"],
	    ["biomesoplenty:seasonal_forest", 52.0, 64.0, "F"],
	    ["byg:frosted_taiga", 22.0, 48.0, "F"],
	    ["atmospheric:flourishing_dunes", 68.0, 105.0, "F"],
	    ["minecraft:old_growth_birch_forest", 58.0, 72.0, "F"],
	    ["biomesoplenty:clover_patch", 56.0, 78.0, "F"],
	    ["minecraft:desert", 48.0, 115.0, "F"],
	    ["minecraft:snowy_taiga", 19.0, 48.0, "F"],
	    ["biomesoplenty:forested_field", 64.0, 78.0, "F"],
	    ["minecraft:deep_frozen_ocean", 56.0, 65.0, "F"],
	    ["biomesoplenty:mediterranean_forest", 64.0, 78.0, "F"],
	    ["minecraft:river", 59, 82, "F"],
	    ["minecraft:old_growth_pine_taiga", 48.0, 62.0, "F"],
	    ["atmospheric:dunes", 78.0, 115.0, "F"],
	    ["biomesoplenty:woodland", 67.0, 80.0, "F"],
	    ["byg:weeping_witch_forest", 56.0, 73.0, "F"],
	    ["biomesoplenty:bog", 62.0, 73.0, "F"],
	    ["byg:twilight_meadow", 49.0, 66.0, "F"],
	    ["byg:autumnal_valley", 58.0, 67.0, "F"],
	    ["minecraft:eroded_badlands", 88.0, 120.0, "F"],
	    ["byg:maple_taiga", 53.0, 71.0, "F"],
	    ["byg:baobab_savanna", 70.0, 95.0, "F"],
	    ["minecraft:bamboo_jungle", 76.0, 87.0, "F"],
	    ["biomesoplenty:maple_woods", 58.0, 68.0, "F"],
	    ["biomesoplenty:marsh", 76.0, 87.0, "F"],
	    ["byg:subzero_hypogeal", -10.0, -10.0, "F"],
	    ["byg:firecracker_shrubland", 72.0, 105.0, "F"],
	    ["minecraft:snowy_beach", 38.0, 52.0, "F"],
	    ["byg:cypress_swamplands", 68.0, 82.0, "F"],
	    ["biomesoplenty:jade_cliffs", 57.0, 70.0, "F"],
	    ["biomesoplenty:mystic_grove", 65.0, 72.0, "F"],
	    ["byg:autumnal_taiga", 56.0, 68.0, "F"],
	    ["atmospheric:rainforest_basin", 68.0, 90.0, "F"],
	    ["biomesoplenty:snowy_fir_clearing", 32.0, 51.0, "F"],
	    ["minecraft:jungle", 76.0, 87.0, "F"],
	    ["minecraft:snowy_slopes", 24.0, 38.0, "F"],
	    ["biomesoplenty:origin_valley", 65.0, 80.0, "F"],
	    ["byg:fragment_forest", 43.0, 64.0, "F"],
	    ["minecraft:soul_sand_valley", 53.0, 53.0, "F"],
	    ["biomesoplenty:dryland", 67.0, 97.0, "F"],
	    ["atmospheric:sparse_rainforest", 62.0, 83.0, "F"],
	    ["atmospheric:petrified_dunes", 58.0, 120.0, "F"],
	    ["minecraft:badlands", 84.0, 120.0, "F"],
	    ["biomesoplenty:volcanic_plains", 82.0, 95.0, "F"],
	    ["biomesoplenty:ominous_woods", 65.0, 72.0, "F"],
	    ["biomesoplenty:snowy_maple_woods", 32.0, 48.0, "F"],
	    ["minecraft:wooded_badlands", 80.0, 108.0, "F"],
	    ["minecraft:windswept_savanna", 67.0, 90.0, "F"],
	    ["byg:frosted_coniferous_forest", 8.0, 31.0, "F"],
	    ["biomesoplenty:lush_desert", 72.0, 94.0, "F"],
	    ["byg:coniferous_forest", 52.0, 70.0, "F"],
	    ["minecraft:plains", 59, 82, "F"]
	]

[Misc]
	#─────────────────────────────────────────────────────────────────────────
	# List of blocks that will allow the player to sleep on them, regardless of the "Prevent Sleep When in Danger" setting
	# Use this list if the player is not getting the temperature effect from sleeping on particular blocks
	"Sleep Check Override Blocks" = ["#comforts:sleeping_bags"]
	#─────────────────────────────────────────────────────────────────────────
	# Converts damage dealt by Soul Fire to cold damage (default: true)
	# Does not affect the block's temperature
	"Cold Soul Fire" = true
	#─────────────────────────────────────────────────────────────────────────
	# When set to true, players cannot sleep if they are cold or hot enough to die
	"Check Sleeping Conditions" = true
	#─────────────────────────────────────────────────────────────────────────
	# A temperature offset applied when in complete shade or when the sky is overcast
	# └── Format: [offset, *units]
	"Shade Temperature Offset" = [-9, "f"]

[Blocks]
	#─────────────────────────────────────────────────────────────────────────//v
	# Applies temperature-emitting properties to blocks
	# ├── Format: [["block_id", temperature, range, *units, *maxEffect, *"predicates", *"{nbt}", *tempLimit], [...], etc]
	# └── [* = optional]
	# • block_id: The ID of the block (i.e. "minecraft:lava")
	# • temperature: The temperature of the block, in Minecraft units
	# • range: The radius of the block's temperature effect, in blocks
	# • *units: The units of the temperature ("f", "c", or "mc"). Defaults to Minecraft units (mc))
	# • *maxEffect: The maximum cumulative temperature change this block can cause to a player (even with multiple blocks)
	# • *predicates: The state that the block must have for the temperature to be applied (i.e. "lit=true").
	#   (Define multiple predicates by separating them with commas [i.e. "lit=true,waterlogged=false"])
	# • *nbt: The NBT data that the block must have for the temperature to be applied.
	# • *tempLimit: The maximum world temperature at which this block temp will have any effect.
	#   (Represents the minimum temp if the block temp is negative)
	"Block Temperatures" = [
	    ["cold_sweat:boiler", 0.27, 7, "mc", 0.88, "lit=true", "", 4],
	    ["cold_sweat:icebox", -0.27, 7, "mc", 0.88, "frosted=true", "", 0],
	    ["#minecraft:fire", 0.476, 7, "mc", 0.9, "", "", 8],
	    ["#minecraft:campfires", 0.476, 7, "mc", 0.9, "lit=true", " ", 8],
	    ["minecraft:magma_block", 0.25, 3, "mc", 1.0],
	    ["minecraft:lava_cauldron", 0.5, 7, "mc", 1.5],
	    ["minecraft:ice", -0.15, 4, "mc", 0.6, "", "", -0.7],
	    ["minecraft:packed_ice", -0.25, 4, "mc", 1.0, "", "", -0.7],
	    ["minecraft:blue_ice", -0.35, 4, "mc", 1.4, "", "", -0.7],
	    ["#minecraft:ice", -0.15, 4, "mc", 0.6, "", "", -0.7],
	    ["minecraft:lava", 0.25, 7, "mc", 4, "", "", 21.5, true],
	    ["create:blaze_burner", 5, 3, "f", 30, "blaze=smouldering", "", 400]
	]
	#─────────────────────────────────────────────────────────────────────────
	# The maximum range of blocks' area of effect
	# - Note: This will not change anything unless blocks are configured to utilize the expanded range
	# - This value is limited to 16 for performance reasons
	#Range: 1 ~ 16
	"Block Range" = 7
	#─────────────────────────────────────────────────────────────────────────
	# When set to true, uses Cold Sweat's temperature system to determine water freezing behavior
	"Custom Freezing Behavior" = true
	#─────────────────────────────────────────────────────────────────────────
	# When set to true, modifies ice blocks to be harvestable with a pickaxe and tweaks its mining speed
	"Custom Ice Drops" = true
	#─────────────────────────────────────────────────────────────────────────
	# The speed at which wet players dry off
	#Range: 0.0 ~ Infinity
	"Dryoff Speed" = 0.0015
	#─────────────────────────────────────────────────────────────────────────
	# The speed at which players become soaked when in water
	#Range: 0.0 ~ Infinity
	"Water Soak Speed" = 0.1
	#─────────────────────────────────────────────────────────────────────────
	# The speed at which players become soaked when in rain
	#Range: 0.0 ~ Infinity
	"Rain Soak Speed" = 0.0125
	#─────────────────────────────────────────────────────────────────────────
	# The default temperature of water
	# └── Format: [temperature, *units]
	"Default Water Temperature" = [-10, "f"]
	#─────────────────────────────────────────────────────────────────────────
	# The maximum soak level a player can reach from rain alone (0.0 - 1.0)
	#Range: 0.0 ~ Infinity
	"Max Rain Soak" = 0.2

#"Thermal sources" are blocks that have a smokestack and give frigidness/warmth. like the hearth, boiler, and iceobx
["Thermal Sources"]
	#─────────────────────────────────────────────────────────────────────────
	# How effective thermal sources are at normalizing temperature
	#Range: 0.0 ~ 1.0
	"Thermal Source Strength" = 0.75
	#─────────────────────────────────────────────────────────────────────────
	# List of additional blocks that thermal sources can spread through
	# Use this list if thermal sources aren't spreading through particular blocks that they should
	"Thermal Source Spread Whitelist" = ["minecraft:iron_bars", "#minecraft:leaves", "create:encased_fluid_pipe"]
	#─────────────────────────────────────────────────────────────────────────
	# List of additional blocks that thermal sources spread through
	# Use this list if thermal sources are spreading through particular blocks that they shouldn't
	"Thermal Source Spread Blacklist" = ["minecraft:water"]

	["Thermal Sources".Hearth]
		#─────────────────────────────────────────────────────────────────────────
		# Allows the hearth to automatically turn on/off based on nearby players' temperature
		# If false, it turns on/off by redstone signal instead
		"Automatic Hearth" = false
		#─────────────────────────────────────────────────────────────────────────
		# The distance the hearth's air will travel from a source, like the hearth itself or the end of a pipe
		#Range: > 0
		"Hearth Range" = 20
		#─────────────────────────────────────────────────────────────────────────
		# The maximum distance that air can be piped away from the hearth
		#Range: > 0
		"Max Hearth Range" = 96
		#─────────────────────────────────────────────────────────────────────────
		# The maximum volume of the hearth's area of effect
		#Range: > 1
		"Hearth Volume" = 12000
		#─────────────────────────────────────────────────────────────────────────
		# The time it takes for the hearth to be fully functional after being placed
		#Range: > 0
		"Hearth Warm-Up Time" = 1200
		#─────────────────────────────────────────────────────────────────────────
		# The maximum amount of insulation that the hearth can provide
		#Range: 0 ~ 10
		"Hearth Effect Strength" = 10
		#─────────────────────────────────────────────────────────────────────────
		# How often the hearth consumes fuel (in ticks)
		# Lower numbers cause fuel to be consumed faster. Setting to 0 disables fuel consumption
		#Range: > 0
		"Hearth Fuel Consumption Interval" = 40

	["Thermal Sources".Boiler]
		#─────────────────────────────────────────────────────────────────────────
		# Allows the boiler to automatically turn on/off based on nearby players' temperature
		# If false, it turns on/off by redstone signal instead
		"Automatic Boiler" = false
		#─────────────────────────────────────────────────────────────────────────
		# The distance the boiler's air will travel from a source, like the boiler itself or the end of a pipe
		#Range: > 0
		"Boiler Range" = 16
		#─────────────────────────────────────────────────────────────────────────
		# The maximum distance that air can be piped away from the boiler
		#Range: > 0
		"Max Boiler Range" = 96
		#─────────────────────────────────────────────────────────────────────────
		# The maximum volume of the boiler's area of effect
		#Range: > 1
		"Boiler Volume" = 2000
		#─────────────────────────────────────────────────────────────────────────
		# The time it takes for the boiler to be fully functional after being placed
		#Range: > 0
		"Boiler Warm-Up Time" = 1200
		#─────────────────────────────────────────────────────────────────────────
		# The maximum amount of insulation that the boiler can provide
		#Range: 0 ~ 10
		"Boiler Warmth Strength" = 5
		#─────────────────────────────────────────────────────────────────────────
		# How often the boiler consumes fuel (in ticks)
		# Lower numbers cause fuel to be consumed faster. Setting to 0 disables fuel consumption
		#Range: > 0
		"Boiler Fuel Consumption Interval" = 40

	["Thermal Sources".Icebox]
		#─────────────────────────────────────────────────────────────────────────
		# Allows the icebox to automatically turn on/off based on nearby players' temperature
		# If false, it turns on/off by redstone signal instead
		"Automatic Icebox" = false
		#─────────────────────────────────────────────────────────────────────────
		# The distance the icebox's air will travel from a source, like the icebox itself or the end of a pipe
		#Range: > 0
		"Icebox Range" = 16
		#─────────────────────────────────────────────────────────────────────────
		# The maximum distance that air can be piped away from the icebox
		#Range: > 0
		"Max Icebox Range" = 96
		#─────────────────────────────────────────────────────────────────────────
		# The maximum volume of the icebox's area of effect
		#Range: > 1
		"Icebox Volume" = 2000
		#─────────────────────────────────────────────────────────────────────────
		# The time it takes for the icebox to be fully functional after being placed
		#Range: > 0
		"Icebox Warm-Up Time" = 1200
		#─────────────────────────────────────────────────────────────────────────
		# The maximum amount of insulation that the icebox can provide
		#Range: 0 ~ 10
		"Icebox Chill Strength" = 5
		#─────────────────────────────────────────────────────────────────────────
		# How often the icebox consumes fuel (in ticks)
		# Lower numbers cause fuel to be consumed faster. Setting to 0 disables fuel consumption
		#Range: > 0
		"Icebox Fuel Consumption Interval" = 40

[Structures]
	#─────────────────────────────────────────────────────────────────────────
	# Overrides the world temperature when the player is within this structure
	# ├── Format: [["structure_id", temperature, *units], [...], etc]
	# └── [* = optional]
	# • structure_id: The ID of the structure (i.e. "minecraft:stronghold")
	# • temperature: The temperature of the structure, in Minecraft units
	# • *units: The units of the temperature ("f" for Fahrenheit, "c" for Celsius, "mc" for Minecraft units)
	"Structure Temperatures" = []
	#─────────────────────────────────────────────────────────────────────────
	# Offsets the world temperature when the player is within this structure
	# ├── Format: [["structure_id", offset, *units], [...], etc]
	# └── [* = optional]
	# • structure_id: The ID of the structure (i.e. "minecraft:igloo")
	# • offset: The temperature offset of the structure, in Minecraft units
	# • *units: The units of the temperature ("f" for Fahrenheit, "c" for Celsius, "mc" for Minecraft units)
	"Structure Temperature Offsets" = []

